### ISSUE TITLE
资源链接失效

### ISSUE THREAD

**Issue by zhangzhengstrive** [josonle/Coding-Now#2]
您好，你分享的资源很棒，非常感谢分享。
但是有几个资源没有找到，分别是下面这几个：
"Python3数据分析与挖掘.txt"
"分布式爬虫打造搜索引擎.txt"
"01-基于Spark2.x新闻网大数据实时分析可视化系统项目.txt"
"03-Spark项目实战：爱奇艺用户行为实时分析系统.txt"
"Spark面试宝典"
可以再分享下吗？谢谢。

**Comment by josonle** [comment]
> 您好，你分享的资源很棒，非常感谢分享。
> 但是有几个资源没有找到，分别是下面这几个：
> "Python3数据分析与挖掘.txt"
> "分布式爬虫打造搜索引擎.txt"
> "01-基于Spark2.x新闻网大数据实时分析可视化系统项目.txt"
> "03-Spark项目实战：爱奇艺用户行为实时分析系统.txt"
> "Spark面试宝典"
> 可以再分享下吗？谢谢。

速度保存吧
链接: https://pan.baidu.com/s/1FUIgInupTGcM5MryZ5t1FA 提取码: s9sn 
链接: https://pan.baidu.com/s/1KuBWz_EXTB0kuQ7vrIKzQQ 提取码: vtzd

**Comment by zhangzhengstrive** [comment]
已存，非常感谢。

**Comment by lp890112** [comment]
连接失效，能否分享下@zhangzhengstrive

**Comment by lp890112** [comment]
"01-基于Spark2.x新闻网大数据实时分析可视化系统项目.txt"
"03-Spark项目实战：爱奇艺用户行为实时分析系统.txt"
这两个项目可以分享下吗，谢谢
